[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.14.1",
    "litellm==1.77.1",
    "pydantic-settings>=2.11.0",
]

[tool.uv]
package = false
